name: netflix_app
description: "A new Flutter project."

publish_to: 'none' # Empêche la publication sur pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3
  lottie: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/symbol.png" # Utilisé pour iOS et Android non-adaptatifs
  adaptive_icon_background: "#000000" # Couleur de fond
  adaptive_icon_foreground: "assets/images/symbol.png" # Image au premier plan (Android)



flutter_native_splash: # Configuration pour flutter_native_splash
  color: "#000000"
  image: "assets/images/logo.png"
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
